(() => {
  const CG = (window.CoopGame = window.CoopGame || {});

  CG.CONSTANTS = {
    CANVAS_WIDTH: 960,
    CANVAS_HEIGHT: 528,
    TILE_SIZE: 24,
    MAP_COLS: 40,
    MAP_ROWS: 22,
    GAME_STATES: {
      CLASS_SELECT: "class_select",
      PLAYING: "playing",
      VICTORY: "victory",
      GAME_OVER: "game_over",
    },
    CLASS_DEFS: {
      samurai: {
        name: "武士",
        color: "#e76f51",
        maxHp: 150,
        speed: 160,
        damage: 32,
        defense: 0.12,
        critChance: 0.08,
        critDamage: 1.55,
        lifeSteal: 0.04,
        attackCooldown: 0.45,
        rollSpeed: 360,
        rollDuration: 0.23,
        weapon: "太刀",
      },
      archer: {
        name: "弓箭手",
        color: "#2a9d8f",
        maxHp: 105,
        speed: 185,
        damage: 20,
        defense: 0.06,
        critChance: 0.12,
        critDamage: 1.7,
        lifeSteal: 0.02,
        attackCooldown: 0.32,
        projectileSpeed: 440,
        rollSpeed: 390,
        rollDuration: 0.21,
        weapon: "复合弓",
      },
      mage: {
        name: "魔法师",
        color: "#3a86ff",
        maxHp: 95,
        speed: 170,
        damage: 24,
        defense: 0.04,
        critChance: 0.1,
        critDamage: 1.6,
        lifeSteal: 0.03,
        attackCooldown: 0.56,
        projectileSpeed: 320,
        rollSpeed: 350,
        rollDuration: 0.25,
        weapon: "法杖",
      },
    },
    SKILL_DEFS: {
      samurai: {
        name: "旋风斩",
        description: "对周围敌人造成高额范围伤害",
        cooldown: 8,
      },
      archer: {
        name: "三连射",
        description: "朝前方发射扇形三连箭",
        cooldown: 6,
      },
      mage: {
        name: "奥术爆发",
        description: "以自身为中心造成范围魔法伤害",
        cooldown: 9,
      },
    },
    ENEMY_DEFS: {
      grunt: {
        name: "小怪",
        color: "#ff9f1c",
        maxHp: 50,
        speed: 100,
        damage: 12,
        attackCooldown: 0.8,
        radius: 14,
      },
      tank: {
        name: "重甲怪",
        color: "#9a8c98",
        maxHp: 95,
        speed: 70,
        damage: 18,
        attackCooldown: 1.1,
        radius: 17,
      },
      shooter: {
        name: "投弹怪",
        color: "#4cc9f0",
        maxHp: 45,
        speed: 85,
        damage: 9,
        attackCooldown: 1.4,
        radius: 13,
        ranged: true,
        projectileSpeed: 220,
      },
    },
    SLOT_KEYS: ["weapon", "armor", "boots", "accessory"],
    SLOT_LABELS: {
      weapon: "武器",
      armor: "衣服",
      boots: "鞋子",
      accessory: "饰品",
    },
    ITEM_PREFIX: {
      weapon: ["锋锐", "猎魔", "破甲", "御风"],
      armor: ["守护", "圣盾", "鳞甲", "韧化"],
      boots: ["疾行", "游侠", "影步", "疾风"],
      accessory: ["秘银", "焰心", "霜语", "星辉"],
    },
    ITEM_RARITY: [
      { key: "common", name: "普通", color: "#cfd8dc", weight: 60, mul: 1 },
      { key: "rare", name: "稀有", color: "#64b5f6", weight: 27, mul: 1.25 },
      { key: "epic", name: "史诗", color: "#ba68c8", weight: 10, mul: 1.55 },
      { key: "legendary", name: "传说", color: "#ffb74d", weight: 3, mul: 1.95 },
    ],
    CONTROL_SETS: {
      p1: {
        up: "KeyW",
        down: "KeyS",
        left: "KeyA",
        right: "KeyD",
        attack: "KeyF",
        roll: "KeyG",
        skill: "KeyR",
        potion: "KeyT",
        interact: "KeyE",
        bagPrev: "KeyC",
        bagNext: "KeyV",
        bagEquip: "KeyB",
        bagDrop: "KeyX",
      },
      p2: {
        up: "KeyI",
        down: "KeyK",
        left: "KeyJ",
        right: "KeyL",
        attack: "KeyH",
        roll: "KeyY",
        skill: "KeyP",
        potion: "BracketLeft",
        interact: "KeyO",
        bagPrev: "KeyN",
        bagNext: "KeyM",
        bagEquip: "Comma",
        bagDrop: "Period",
      },
    },
    CLASS_PICK_KEYS: {
      p1: { KeyQ: "samurai", KeyW: "archer", KeyE: "mage" },
      p2: { KeyU: "samurai", KeyI: "archer", KeyO: "mage" },
    },
  };
})();
